'use client';
import {useEffect,useRef,useState} from 'react';
import {X,Play,Star} from 'lucide-react';
import {motion} from 'framer-motion';
import type {Movie} from '@/lib/types';
import MovieArt from './MovieArt';
export default function MovieModal({movie,autoplay,onClose,onRate}: {movie:Movie;autoplay:boolean;onClose:()=>void;onRate:(m:Movie,r:number)=>void}) {
  const dialog=useRef<HTMLDialogElement>(null), [playing,setPlaying]=useState(autoplay && !!movie.trailer_key),[rating,setRating]=useState(0);
  useEffect(()=>{const el=dialog.current;el?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el?.close();document.body.style.overflow=previous;};},[]);
  return <dialog ref={dialog} className="movie-dialog" onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}}><button className="modal-close icon-button" aria-label="Close movie details" onClick={onClose}><X/></button><div className="modal-art">{playing && movie.trailer_key ? <iframe src={`https://www.youtube-nocookie.com/embed/${movie.trailer_key}?autoplay=1&rel=0`} title={`${movie.title} trailer`} allow="autoplay; encrypted-media; fullscreen" allowFullScreen/>:<MovieArt movie={movie} backdrop/>}</div><div className="modal-body"><div className="eyebrow">CINEVERSE · MOVIE DETAILS</div><h2>{movie.title}</h2><div className="movie-meta"><strong className="match">★ {movie.rating.toFixed(1)} / 5</strong><span>{movie.year}</span>{movie.runtime && <span>{movie.runtime} min</span>}<span>{movie.rating_count} ratings</span></div><p>{movie.overview}</p><div className="genre-tags">{movie.genres.map(g=><span key={g}>{g}</span>)}</div>{movie.trailer_key ? <button className="button button-white" onClick={()=>setPlaying(true)}><Play size={18}/>Play trailer</button>:<p className="muted">A trailer is not available for this title.</p>}<div className="rating-panel"><div><h3>Your rating</h3><p>Help us find more of what you love.</p></div><div className="stars">{[1,2,3,4,5].map(n=><button key={n} aria-label={`Rate ${n} out of 5`} aria-pressed={rating===n} onClick={()=>{setRating(n);onRate(movie,n);}}><Star size={24} fill={n<=rating ? '#e50914':'none'} color={n<=rating ? '#e50914':'#999'}/></button>)}</div></div>{movie.directors && <p className="credits"><b>Directed by</b> {movie.directors}</p>}<p className="credits">{movie.metadata_source==='tmdb' ? 'Movie metadata provided by TMDB.':'Catalog description. Connect TMDB for official artwork and synopsis.'}</p></div></motion.div></dialog>;
}
