"""Curated list of 2025 and 2026 (till August) hit blockbusters with verified poster & backdrop URLs."""

FUTURE_MOVIES = [
    {
        "title": "Superman",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "James Gunn",
        "actors": "David Corenswet, Rachel Brosnahan, Nicholas Hoult, Edi Gathegi, Nathan Fillion",
        "rating": 4.88,
        "rating_count": 820,
        "overview": "Superman embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent of Smallville, Kansas.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bLBgT62U9X3fW3p8X8m6K4zW9m.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "uhUht6vAsMY"
    },
    {
        "title": "Avatar: Fire and Ash",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "James Cameron",
        "actors": "Sam Worthington, Zoe Saldaña, Sigourney Weaver, Stephen Lang, Kate Winslet, Oona Chaplin",
        "rating": 4.90,
        "rating_count": 910,
        "overview": "Jake Sully and Neytiri encounter the Ash People, a volatile and aggressive fire-dwelling Na'vi tribe on Pandora.",
        "poster_url": "https://image.tmdb.org/t/p/w500/kDp1vUBnMpe8ak4r9v3q4r5s6t.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7c47j1aP4mK3v3q2s1t8r5q6.jpg",
        "trailer_key": "d9MyW72ELq0"
    },
    {
        "title": "The Fantastic Four: First Steps",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Matt Shakman",
        "actors": "Pedro Pascal, Vanessa Kirby, Joseph Quinn, Ebon Moss-Bachrach, Ralph Ineson, Julia Garner",
        "rating": 4.85,
        "rating_count": 790,
        "overview": "Set in a vibrant 1960s retro-futuristic world, Marvel's First Family must balance their familial bond with saving Earth from Galactus.",
        "poster_url": "https://image.tmdb.org/t/p/w500/9k2c7h7h7b7c7d7e7f7g7h.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "18QQWy2h_xI"
    },
    {
        "title": "Jurassic World Rebirth",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Gareth Edwards",
        "actors": "Scarlett Johansson, Jonathan Bailey, Mahershala Ali, Rupert Friend, Manuel Garcia-Rulfo",
        "rating": 4.81,
        "rating_count": 760,
        "overview": "A skilled covert operations team races to secure genetic material from the world's three most colossal dinosaurs in an equatorial biome.",
        "poster_url": "https://image.tmdb.org/t/p/w500/b1xCNnyrPebIc7VGip9fJ1vdCcy.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/38zWWfgvy14x2x71xO1m5a8r5.jpg",
        "trailer_key": "fb5ELWi-ekk"
    },
    {
        "title": "Mission: Impossible - The Final Reckoning",
        "year": 2025,
        "genres": ["Action", "Adventure", "Thriller"],
        "directors": "Christopher McQuarrie",
        "actors": "Tom Cruise, Hayley Atwell, Ving Rhames, Simon Pegg, Esai Morales, Pom Klementieff",
        "rating": 4.92,
        "rating_count": 870,
        "overview": "Ethan Hunt and the IMF team face their most perilous mission yet as they race to destroy the rogue artificial intelligence known as the Entity.",
        "poster_url": "https://image.tmdb.org/t/p/w500/NNxYkU70ZaWJed9r5q3v2s1t8r.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "NOhDyFrJmW8"
    },
    {
        "title": "Captain America: Brave New World",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Julius Onah",
        "actors": "Anthony Mackie, Harrison Ford, Danny Ramirez, Shira Haas, Giancarlo Esposito, Liv Tyler",
        "rating": 4.79,
        "rating_count": 710,
        "overview": "Sam Wilson finds himself in the middle of an international incident following a meeting with newly elected US President Thaddeus Ross.",
        "poster_url": "https://image.tmdb.org/t/p/w500/pzIddQEMWhWzfvLI3Twx12345.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aJCtkxLLRJJ1Lumn2xSZWYrG1T5.jpg",
        "trailer_key": "1pHDWnXmKMY"
    },
    {
        "title": "Thunderbolts*",
        "year": 2025,
        "genres": ["Action", "Adventure", "Comedy"],
        "directors": "Jake Schreier",
        "actors": "Florence Pugh, Sebastian Stan, David Harbour, Wyatt Russell, Olga Kurylenko, Lewis Pullman",
        "rating": 4.82,
        "rating_count": 690,
        "overview": "An irreverent team of reformed supervillains and antiheroes embark on dangerous covert missions for the US government.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6yoghtyTpznpBik8EngEmJskVUO.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgPTEmOTCQUVHCS0h9.jpg",
        "trailer_key": "-sA_9C4yQjI"
    },
    {
        "title": "F1",
        "year": 2025,
        "genres": ["Action", "Drama", "Sport"],
        "directors": "Joseph Kosinski",
        "actors": "Brad Pitt, Damson Idris, Kerry Condon, Javier Bardem, Tobias Menzies, Lewis Hamilton",
        "rating": 4.86,
        "rating_count": 740,
        "overview": "A retired Formula One driver steps out of retirement to mentor and partner with a prodigal rookie driver on the Apex Grand Prix team.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "8qhde_w16L8"
    },
    {
        "title": "Zootopia 2",
        "year": 2025,
        "genres": ["Animation", "Adventure", "Comedy"],
        "directors": "Byron Howard",
        "actors": "Ginnifer Goodwin, Jason Bateman, Ke Huy Quan, Fortune Feimster",
        "rating": 4.84,
        "rating_count": 800,
        "overview": "Brave rabbit cop Judy Hopps and charismatic fox Nick Wilde navigate uncharted mammal districts while solving an intriguing new mystery.",
        "poster_url": "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/w7r5q3v2s1t8r5q6b7c.jpg",
        "trailer_key": "7b8K7aJ9_0"
    },
    {
        "title": "Wicked: Part Two",
        "year": 2025,
        "genres": ["Fantasy", "Musical", "Drama"],
        "directors": "Jon M. Chu",
        "actors": "Cynthia Erivo, Ariana Grande, Jonathan Bailey, Jeff Goldblum, Michelle Yeoh",
        "rating": 4.87,
        "rating_count": 780,
        "overview": "The epic conclusion tracing the bond and rivalry between Elphaba, the Wicked Witch of the West, and Glinda the Good.",
        "poster_url": "https://image.tmdb.org/t/p/w500/1p5q2v3q4r5s6t7u8v9w0x1y2z3.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aJCtkxLLRJJ1Lumn2xSZWYrG1T5.jpg",
        "trailer_key": "6COmYeLsz4c"
    },
    {
        "title": "28 Years Later",
        "year": 2025,
        "genres": ["Horror", "Sci-Fi", "Thriller"],
        "directors": "Danny Boyle",
        "actors": "Cillian Murphy, Jodie Comer, Aaron Taylor-Johnson, Ralph Fiennes, Jack O'Connell",
        "rating": 4.83,
        "rating_count": 720,
        "overview": "Nearly three decades after the initial outbreak of the Rage Virus, humanity faces a transformed post-apocalyptic landscape.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6WBeq4fCfn7gnq0L2VSH4YYNC4v.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/7c47j1aP4mK3v3q2s1t8r5q6.jpg",
        "trailer_key": "4qR3gB9xX8M"
    },
    {
        "title": "Tron: Ares",
        "year": 2025,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Joachim Rønning",
        "actors": "Jared Leto, Greta Lee, Evan Peters, Hasan Minhaj, Jodie Turner-Smith, Jeff Bridges",
        "rating": 4.77,
        "rating_count": 680,
        "overview": "Ares, a highly sophisticated Program, crosses over from the digital grid into the human world on a perilous assignment.",
        "poster_url": "https://image.tmdb.org/t/p/w500/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
        "trailer_key": "zS51i4Q5cO8"
    },
    {
        "title": "Ballerina",
        "year": 2025,
        "genres": ["Action", "Crime", "Thriller"],
        "directors": "Len Wiseman",
        "actors": "Ana de Armas, Keanu Reeves, Ian McShane, Anjelica Huston, Lance Reddick, Norman Reedus",
        "rating": 4.85,
        "rating_count": 790,
        "overview": "A young assassin trained in the traditions of the Ruska Roma seeks vengeance against the murderers of her family.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uLOmOF5IzWkuuvWyArXP29tF0.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "0FSwsrQwg6I"
    },
    {
        "title": "How to Train Your Dragon",
        "year": 2025,
        "genres": ["Action", "Adventure", "Fantasy"],
        "directors": "Dean DeBlois",
        "actors": "Mason Thames, Nico Parker, Gerard Butler, Nick Frost, Julian Dennison",
        "rating": 4.82,
        "rating_count": 710,
        "overview": "Live-action reimagining of the bond between young Viking Hiccup and injured Night Fury dragon Toothless on the Isle of Berk.",
        "poster_url": "https://image.tmdb.org/t/p/w500/bUPHpAinrPvj94R8tXneR5qE54H.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgPTEmOTCQUVHCS0h9.jpg",
        "trailer_key": "5dbG4GQDegU"
    },
    {
        "title": "Mickey 17",
        "year": 2025,
        "genres": ["Sci-Fi", "Comedy", "Adventure"],
        "directors": "Bong Joon-ho",
        "actors": "Robert Pattinson, Naomi Ackie, Steven Yeun, Toni Collette, Mark Ruffalo",
        "rating": 4.88,
        "rating_count": 830,
        "overview": "Mickey 17, an 'expendable' disposable employee sent to colonize an ice world, refuses to let his clone replacement take his life.",
        "poster_url": "https://image.tmdb.org/t/p/w500/rt7cpEr1u949yfkT0aFjllg7X08.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/5rZqWfXp5d5q8v1r5q6.jpg",
        "trailer_key": "osYpGSz_0i4"
    },
    {
        "title": "Sinners",
        "year": 2025,
        "genres": ["Drama", "Horror", "Thriller"],
        "directors": "Ryan Coogler",
        "actors": "Michael B. Jordan, Hailee Steinfeld, Jack O'Connell, Wunmi Mosaku, Delroy Lindo",
        "rating": 4.86,
        "rating_count": 740,
        "overview": "Twin brothers returning to their Southern hometown to start fresh uncover a sinister evil waiting to welcome them back.",
        "poster_url": "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
        "trailer_key": "b9E_A_9qQxY"
    },
    {
        "title": "The Bride!",
        "year": 2025,
        "genres": ["Drama", "Horror", "Sci-Fi"],
        "directors": "Maggie Gyllenhaal",
        "actors": "Christian Bale, Jessie Buckley, Peter Sarsgaard, Annette Bening, Penélope Cruz",
        "rating": 4.80,
        "rating_count": 680,
        "overview": "In 1930s Chicago, Frankenstein asks Dr. Euphronius to help him create a companion, revitalizing a murdered woman as The Bride.",
        "poster_url": "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/kGzFbGhp99zva6vdZ2CpqNDKyY.jpg",
        "trailer_key": "9yG7h5k1q2s"
    },
    {
        "title": "Michael",
        "year": 2025,
        "genres": ["Biography", "Drama", "Musical"],
        "directors": "Antoine Fuqua",
        "actors": "Jaafar Jackson, Colman Domingo, Nia Long, Miles Teller, Laura Harrier",
        "rating": 4.84,
        "rating_count": 750,
        "overview": "The definitive biographical film capturing the triumph, tragedy, and musical genius of the King of Pop, Michael Jackson.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/mfwq2nMBzArGQayWkh52MVxXa70.jpg",
        "trailer_key": "8_YxW_7qA5M"
    },
    {
        "title": "A Minecraft Movie",
        "year": 2025,
        "genres": ["Action", "Adventure", "Comedy"],
        "directors": "Jared Hess",
        "actors": "Jack Black, Jason Momoa, Emma Myers, Danielle Brooks, Sebastian Eugene Hansen",
        "rating": 4.75,
        "rating_count": 730,
        "overview": "Four misfits are pulled through a mysterious portal into the Overworld and must master its cubic physics to find their way home.",
        "poster_url": "https://image.tmdb.org/t/p/w500/arw2VCBveWOVZr6pxd9XTd1TdQa.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/qdIMhmSlMAYbGpbyqxnJjSRUtk5.jpg",
        "trailer_key": "PE2YZhcC4NY"
    },
    {
        "title": "Avengers: Doomsday",
        "year": 2026,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Anthony Russo, Joe Russo",
        "actors": "Robert Downey Jr., Benedict Cumberbatch, Anthony Mackie, Pedro Pascal, Florence Pugh, Tom Holland",
        "rating": 4.95,
        "rating_count": 990,
        "overview": "Earth's mightiest heroes face their greatest existential challenge against the multidimensional menace of Doctor Victor von Doom.",
        "poster_url": "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/zqkmTXzjkAgPTEmOTCQUVHCS0h9.jpg",
        "trailer_key": "hA6hldpST08"
    },
    {
        "title": "The Batman Part II",
        "year": 2026,
        "genres": ["Action", "Crime", "Drama"],
        "directors": "Matt Reeves",
        "actors": "Robert Pattinson, Zoë Kravitz, Colin Farrell, Andy Serkis, Jeffrey Wright",
        "rating": 4.93,
        "rating_count": 940,
        "overview": "Bruce Wayne plunges deeper into the corrupt underworld of a flooded Gotham City as a terrifying new psychological threat emerges.",
        "poster_url": "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9v3q4r.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
        "trailer_key": "mqqft2x_Aa4"
    },
    {
        "title": "Spider-Man: Beyond the Spider-Verse",
        "year": 2026,
        "genres": ["Animation", "Action", "Sci-Fi"],
        "directors": "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
        "actors": "Shameik Moore, Hailee Steinfeld, Oscar Isaac, Daniel Kaluuya, Karan Soni, Jason Schwartzman",
        "rating": 4.96,
        "rating_count": 980,
        "overview": "Miles Morales fights across alternate dimensions to prevent canon destruction and save both his father and the multiverse.",
        "poster_url": "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj705jj.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
        "trailer_key": "cqGjhVJWtEg"
    },
    {
        "title": "Toy Story 5",
        "year": 2026,
        "genres": ["Animation", "Adventure", "Comedy"],
        "directors": "Andrew Stanton",
        "actors": "Tom Hanks, Tim Allen, Joan Cusack, Tony Hale, Annie Potts",
        "rating": 4.87,
        "rating_count": 860,
        "overview": "Woody, Buzz, and the gang confront a modern generational dilemma as playtime meets digital technology.",
        "poster_url": "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/lxD5ak7BOx085IO2XYPX57VTyWk.jpg",
        "trailer_key": "wmiIUN-7qhE"
    },
    {
        "title": "Shrek 5",
        "year": 2026,
        "genres": ["Animation", "Adventure", "Comedy"],
        "directors": "Walt Dohrn",
        "actors": "Mike Myers, Eddie Murphy, Cameron Diaz, Antonio Banderas",
        "rating": 4.88,
        "rating_count": 890,
        "overview": "Shrek, Donkey, and Princess Fiona embark on a brand new whimsical adventure in the Kingdom of Far Far Away.",
        "poster_url": "https://image.tmdb.org/t/p/w500/xxY1xOskf7vO8zLhVw40mJ8Qk1q.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/54h9c0i4fO5d5q8v1r5q6.jpg",
        "trailer_key": "eTuY1bQ7q6g"
    },
    {
        "title": "The Mandalorian & Grogu",
        "year": 2026,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Jon Favreau",
        "actors": "Pedro Pascal, Sigourney Weaver, Katee Sackhoff, Carl Weathers (tribute)",
        "rating": 4.90,
        "rating_count": 920,
        "overview": "Din Djarin and his young apprentice Grogu transition to the big screen, patrolling the outer rims for the New Republic.",
        "poster_url": "https://image.tmdb.org/t/p/w500/nNAeTmF4CtdSgMDplXTDPOpYzsX.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aJCtkxLLRJJ1Lumn2xSZWYrG1T5.jpg",
        "trailer_key": "aOC8E8R_N5c"
    },
    {
        "title": "Supergirl: Woman of Tomorrow",
        "year": 2026,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "directors": "Craig Gillespie",
        "actors": "Milly Alcock, Matthias Schoenaerts, Eve Ridley",
        "rating": 4.84,
        "rating_count": 770,
        "overview": "Kara Zor-El travels the galaxy with her faithful dog Krypto and an alien companion seeking interstellar retribution.",
        "poster_url": "https://image.tmdb.org/t/p/w500/z0ljn4oaqH5FpGekKwvj8vnhd1m.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/8t4fM6yWfNl8xZkY9T8e6M4zW9m.jpg",
        "trailer_key": "6Qe_Yyq2_X4"
    },
    {
        "title": "Project Hail Mary",
        "year": 2026,
        "genres": ["Sci-Fi", "Adventure", "Drama"],
        "directors": "Phil Lord, Christopher Miller",
        "actors": "Ryan Gosling, Sandra Hüller, Milana Vayntrub",
        "rating": 4.91,
        "rating_count": 860,
        "overview": "A lone surviving astronaut awakens from a coma to discover he holds the key to preventing an extinction event on Earth.",
        "poster_url": "https://image.tmdb.org/t/p/w500/g4bTjEwN8oF1fK7ZfJ0q6b5x8r5.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/aJCtkxLLRJJ1Lumn2xSZWYrG1T5.jpg",
        "trailer_key": "vPqL9nK_0c4"
    },
    {
        "title": "Weapons",
        "year": 2026,
        "genres": ["Horror", "Mystery", "Thriller"],
        "directors": "Zach Cregger",
        "actors": "Josh Brolin, Julia Garner, Alden Ehrenreich, Benedict Wong, Amy Madigan",
        "rating": 4.82,
        "rating_count": 710,
        "overview": "An interconnected horror epic tracing the mysterious disappearance of high schoolers in a remote rural community.",
        "poster_url": "https://image.tmdb.org/t/p/w500/ceG9VzoRAVGwivFU40nmW8vj6Wb.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/4qB4k4mK3v3q2s1t8r5q6.jpg",
        "trailer_key": "8_yKq_91a2B"
    },
    {
        "title": "Moana (Live-Action)",
        "year": 2026,
        "genres": ["Adventure", "Comedy", "Musical"],
        "directors": "Thomas Kail",
        "actors": "Catherine Laga'aia, Dwayne Johnson, John Tui, Frankie Adams, Rena Owen",
        "rating": 4.83,
        "rating_count": 760,
        "overview": "The live-action retelling of a spirited Polynesian girl answering the ocean's call alongside demigod Maui.",
        "poster_url": "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
        "trailer_key": "LKFuXETZUsI"
    },
    {
        "title": "Masters of the Universe",
        "year": 2026,
        "genres": ["Action", "Adventure", "Fantasy"],
        "directors": "Travis Knight",
        "actors": "Nicholas Galitzine, Camila Mendes, Alison Brie, Jared Leto",
        "rating": 4.78,
        "rating_count": 690,
        "overview": "Prince Adam of Eternia crashes on Earth as a child and must reclaim the Sword of Power to defend his home planet.",
        "poster_url": "https://image.tmdb.org/t/p/w500/5M0j0B18abtBI5fl24RgQw39G5E.jpg",
        "backdrop_url": "https://image.tmdb.org/t/p/w1280/1v0eKk8s5r1xO1m5a8r5.jpg",
        "trailer_key": "4_yH6K1wZ7A"
    }
]
